// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpkojxspckdylzvlxscx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwa29qeHNwY2tkeWx6dmx4c2N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjEyMzksImV4cCI6MjA2NzUzNzIzOX0.4pn384mVRx6CDklt4rQ5xp_un5PsLFisNMoOxx7D8nI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});